name: Auto Merge

on: [pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.inputs.pull-request }}
          pull-request-author-associations: 'github-actions'
          required-labels: auto
