name: Auto Merge

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - if: "github.actor == 'mattlove-github-robot[bot]'"
        name: Check User
        run: |
          echo "${{ github.actor }} not authorized to automerge"
          exit 1

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: '${{ secrets.ROBOT_APP_ID }}'
          private_key: '${{ secrets.ROBOT_APP_PRIVATE_KEY }}'

      - name: Merge
        uses: reitermarkus/automerge@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request: ${{ github.event.inputs.pull-request }}
          required-labels: auto
