name: Build

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Prepare
        id: build
        run: pnpm --silent run build

      - if: "steps.build.outputs.version == 'no-update'"
        run: |
          echo "version=${{ steps.build.outputs.version }}"
          echo "No Update Needed"
          exit 0

      - if: "steps.build.outputs.complete == 'true'"
        run: |
          echo "version=${{ steps.build.outputs.version }}"
          git checkout -b "auto-update-${{ steps.build.outputs.version }}"
          git add .
          git commit -m "Update Cloudflare Worker Types to ${{ steps.build.outputs.version }}"

      # - if: "steps.build.outputs.complete == 'true'"
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: Update Cloudflare Worker Types to ${{ steps.build.outputs.version }}
      #     branch: 'auto-update-${{ steps.build.outputs.version }}'

      - if: "steps.build.outputs.complete == 'true'"
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          labels: auto
          branch: 'auto-update-${{ steps.build.outputs.version }}'
