name: Build

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Prepare
        id: build
        run: pnpm build

      - if: "steps.build.outputs.version == 'no-update'"
        run: |
          echo "No Update Needed"
          exit 0

      - if: "steps.build.outputs.version != 'no-update'"
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update Cloudflare Worker Types to ${{ steps.build.outputs.version }}

      - if: "steps.build.outputs.version != 'no-update'"
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          labels: auto
