name: Build

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Prepare
        id: build
        run: pnpm --silent run build

      - if: "steps.build.outputs.version == 'no-update'"
        run: |
          echo "version=${{ steps.build.outputs.version }}"
          echo "No Update Needed"
          exit 0

      - if: "steps.build.outputs.complete == 'true'"
        name: 'Set Branch Name'
        run: |
          echo 'BRANCH_NAME=auto-update-${{ steps.build.outputs.version }}-${{ github.run_id }}${{ github.run_number }}${{ github.run_attempt }}' >> $GITHUB_ENV
          echo "version=${{ steps.build.outputs.version }}"

      - if: "steps.build.outputs.complete == 'true'"
        name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: '${{ secrets.ROBOT_APP_ID }}'
          private_key: '${{ secrets.ROBOT_APP_PRIVATE_KEY }}'

      - if: "steps.build.outputs.complete == 'true'"
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          labels: auto
          base: main
          branch: '${{ env.BRANCH_NAME }}'
          title: 'Update Cloudflare Worker Types to ${{ steps.build.outputs.version }}'
          commit-message: 'Update Cloudflare Worker Types to ${{ steps.build.outputs.version }}'
