name: Publish

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

jobs:
  publish:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: '${{ secrets.ROBOT_APP_ID }}'
          private_key: '${{ secrets.ROBOT_APP_PRIVATE_KEY }}'

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Prepare
        id: build
        run: pnpm --silent run build

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          token: ${{ steps.generate_token.outputs.token }}
          files: |
            LICENSE
            package.json
            dist/**/*

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
